'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,LayoutDashboard,Waypoints,Files,RotateCcw,ChartNoAxesCombined,Library,Flame,ArrowRight,Check,X,ShieldCheck,ChevronRight,Download,Upload,CheckCircle2,LockKeyhole,Stamp,Scale,ArrowLeft,Share2,Heart,Target,Smartphone} from 'lucide-react';
import {cases as initialCases,chapters,type Case} from '../lib/cases';
import {supabase} from '../lib/supabase';
type Attempt={id:string;case_id:string;mode:string;chapter:number;choice:number;correct:number;hint:number;duration:number;created:string};
type LocalProgress={attempts:Attempt[];cases:Case[]};
const STORAGE_KEY='health-law-reviewer-progress-v1';
function readProgress():LocalProgress{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return {attempts:[],cases:[]};const data=JSON.parse(raw);return {attempts:Array.isArray(data.attempts)?data.attempts:[],cases:Array.isArray(data.cases)?data.cases:[]};}catch{return {attempts:[],cases:[]};}}
function writeProgress(data:LocalProgress){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
const day=(d:Date|string)=>new Date(d).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});
const modes:Record<string,string>={story:'스토리 심사',free:'자유 심사',review:'오답 재심사',audit:'감사 재심사'};
const nav=[['home','오늘의 심사실',LayoutDashboard],['story','스토리 모드',Waypoints],['free','자유 심사',Files],['review','오답 재심사',RotateCcw],['stats','학습 기록',ChartNoAxesCombined],['bank','문항 관리',Library]] as const;
function download(name:string,content:string,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function App(){
const [tab,setTab]=useState('home'),[bank,setBank]=useState<Case[]>(initialCases),[attempts,setAttempts]=useState<Attempt[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('전체'),[difficulty,setDifficulty]=useState('전체'),[search,setSearch]=useState('');
const [session,setSession]=useState<{queue:Case[];index:number;mode:string;right:number}|null>(null),[result,setResult]=useState<boolean|null>(null),[hint,setHint]=useState(false),[usedHint,setUsedHint]=useState(false),[finished,setFinished]=useState(false),[toast,setToast]=useState(''),[guest,setGuest]=useState(true),[sound,setSound]=useState(false),[installPrompt,setInstallPrompt]=useState<any>(null);
const [member,setMember]=useState<{id:string;email:string;nickname:string;isAdmin:boolean}|null>(null);
const [leaders,setLeaders]=useState<{nickname:string;solved:number;correct:number;accuracy:number}[]>([]);
const startTime=useRef(Date.now()),requestId=useRef(''),fileRef=useRef<HTMLInputElement>(null),lock=useRef(false);
const mergeBank=(shared:any[],saved:Case[]=[])=>[...initialCases,...saved,...shared.map((x:any)=>x.payload as Case)].filter((c,i,a)=>a.findIndex(v=>v.id===c.id)===i);
async function load(){setError('');try{const saved=readProgress();if(!supabase){setAttempts(saved.attempts);setBank(mergeBank([],saved.cases));setGuest(true);setReady(true);return;}const {data:{session:authSession}}=await supabase.auth.getSession();const {data:shared}=await supabase.from('shared_cases').select('payload');if(!authSession){setMember(null);setLeaders([]);setAttempts(saved.attempts);setBank(mergeBank(shared||[],saved.cases));setGuest(true);setReady(true);return;}let [{data:rows,error:attemptError},{data:profile},{data:ranking}]=await Promise.all([supabase.from('attempts').select('*').order('created'),supabase.from('profiles').select('nickname,is_admin').eq('id',authSession.user.id).maybeSingle(),supabase.rpc('leaderboard')]);if(!profile){const nickname=String(authSession.user.user_metadata?.nickname||'심사관').slice(0,20);const {data}=await supabase.from('profiles').upsert({id:authSession.user.id,nickname}).select('nickname,is_admin').single();profile=data;}if(attemptError)throw new Error('서버 기록을 불러오지 못했습니다.');setMember({id:authSession.user.id,email:authSession.user.email||'',nickname:profile?.nickname||'심사관',isAdmin:!!profile?.is_admin});setLeaders((ranking||[]) as {nickname:string;solved:number;correct:number;accuracy:number}[]);setAttempts((rows||[]) as Attempt[]);setBank(mergeBank(shared||[],saved.cases));setGuest(false);setReady(true);}catch(e){setError((e as Error).message);}}
async function accountAction(){if(!supabase){setToast('회원 서버를 연결하는 중입니다.');return;}if(member){if(confirm('로그아웃할까요?')){await supabase.auth.signOut();setMember(null);setToast('로그아웃했습니다.');await load();}return;}const signup=confirm('확인을 누르면 회원가입, 취소를 누르면 로그인입니다.');const email=prompt('이메일 주소를 입력하세요.');const password=prompt('비밀번호를 입력하세요. (8자 이상 권장)');if(!email||!password)return;if(signup){const nickname=prompt('앱에서 표시할 닉네임을 입력하세요. (2~20자)');if(!nickname)return;const {data,error}=await supabase.auth.signUp({email,password,options:{data:{nickname}}});if(error){setError(error.message);return;}if(data.user&&data.session)await supabase.from('profiles').upsert({id:data.user.id,nickname});setToast(data.session?'회원가입되었습니다.':'인증 메일을 확인한 뒤 로그인하세요.');}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);return;}setToast('로그인했습니다.');}await load();}
useEffect(()=>{load();},[]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)}},[toast]);
useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const onInstall=(event:any)=>{event.preventDefault();setInstallPrompt(event)};window.addEventListener('beforeinstallprompt',onInstall);return()=>window.removeEventListener('beforeinstallprompt',onInstall)},[]);
const today=day(new Date()),todayAttempts=attempts.filter(a=>day(a.created)===today),correctCount=attempts.filter(a=>a.correct).length,accuracy=attempts.length?Math.round(correctCount/attempts.length*100):0;
const xp=attempts.reduce((v,a)=>Math.max(0,v+(a.correct?20:-5)),0),level=Math.min(4,Math.floor(xp/100));
const latest=new Map<string,Attempt>();attempts.forEach(a=>latest.set(a.case_id,a));const wrong=bank.filter(c=>latest.has(c.id)&&!latest.get(c.id)!.correct);
const days=new Map<string,number>();attempts.forEach(a=>days.set(day(a.created),(days.get(day(a.created))||0)+1));let streak=0;let d=new Date(today+'T12:00:00+09:00');if((days.get(today)||0)<5)d.setDate(d.getDate()-1);while((days.get(day(d))||0)>=5){streak++;d.setDate(d.getDate()-1);}
const storyDone=(ch:number)=>bank.filter(c=>c.chapter===ch&&attempts.some(a=>a.case_id===c.id&&a.mode==='story')).length;
const storyTotal=(ch:number)=>bank.filter(c=>c.chapter===ch).length;
const openChapter=chapters.findIndex((_,i)=>storyDone(i)<storyTotal(i));
const current=session?.queue[session.index];const laws=Array.from(new Set(bank.map(c=>c.law)));
function go(t:string){if(busy)return;setTab(t);setSession(null);setFinished(false);setError('');setFilter('전체');window.scrollTo({top:0,behavior:'smooth'});}
async function installApp(){if(!installPrompt){setToast('브라우저 메뉴에서 “홈 화면에 추가”를 선택하면 앱처럼 설치할 수 있습니다.');return;}installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);}
function begin(queue:Case[],mode:string){if(!ready||!queue.length)return;setSession({queue,index:0,mode,right:0});setResult(null);setHint(false);setUsedHint(false);setFinished(false);startTime.current=Date.now();requestId.current=crypto.randomUUID();}
async function answer(choice:boolean){if(!current||!session||result!==null||lock.current)return;lock.current=true;setBusy(true);setError('');try{const correct=current.answer===choice;const attempt:Attempt={id:requestId.current,case_id:current.id,mode:session.mode,chapter:current.chapter,choice:Number(choice),correct:Number(correct),hint:usedHint?1:0,duration:Math.min(86400,Math.floor((Date.now()-startTime.current)/1000)),created:new Date().toISOString()};const nextAttempts=[...attempts,attempt];if(member&&supabase){const {error}=await supabase.from('attempts').insert({...attempt,user_id:member.id,choice:choice,correct,hint:usedHint});if(error)throw new Error('서버에 기록을 저장하지 못했습니다.');}else writeProgress({attempts:nextAttempts,cases:bank.filter(c=>c.id.startsWith('custom-'))});setAttempts(nextAttempts);setResult(correct);if(sound){try{const ctx=new AudioContext();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type="triangle";osc.frequency.setValueAtTime(correct?520:180,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(correct?800:90,ctx.currentTime+.14);gain.gain.setValueAtTime(.1,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.2);osc.onended=()=>ctx.close();}catch{}}setSession({...session,right:session.right+(correct?1:0)});}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
function next(){if(!session)return;if(session.index===session.queue.length-1){setFinished(true);return;}setSession({...session,index:session.index+1});setResult(null);setHint(false);setUsedHint(false);startTime.current=Date.now();requestId.current=crypto.randomUUID();}
function freeQueue(){const list=bank.filter(c=>(filter==='전체'||c.law===filter)&&(difficulty==='전체'||c.difficulty===difficulty));return [...list].sort(()=>Math.random()-.5).slice(0,5);}
async function importCases(file:File){setBusy(true);try{if(!member?.isAdmin||!supabase)throw Error('관리자 계정으로 로그인해야 문항을 저장할 수 있습니다.');if(file.size>2000000)throw Error('2MB 이하 JSON 파일을 선택해 주세요.');const list=JSON.parse(await file.text());if(!Array.isArray(list)||!list.length||list.length>200)throw Error('1~200개 문항의 JSON 배열이 필요합니다.');const custom=list.filter((c:unknown):c is Case=>!!c&&typeof c==='object'&&typeof (c as Case).id==='string'&&(c as Case).id.startsWith('custom-'));if(custom.length!==list.length)throw Error('문항 ID는 custom-으로 시작해야 합니다.');const {error}=await supabase.from('shared_cases').upsert(custom.map(payload=>({id:payload.id,payload,updated_at:new Date().toISOString()})));if(error)throw Error('공용 문항 저장에 실패했습니다. 관리자 권한을 확인하세요.');await load();setToast(`${list.length}개 문항을 모든 사용자에게 저장했습니다.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}}
function exportCSV(){const rows=[['사건ID','모드','법령','정답여부','법령도움','소요초','기록시각'],...attempts.map(a=>[a.case_id,modes[a.mode],bank.find(c=>c.id===a.case_id)?.law||'',a.correct?'정답':'오답',a.hint?'사용':'미사용',a.duration,a.created])];download('보건법규_학습기록.csv','\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv;charset=utf-8');}
async function share(){const text=`보건법규 심사관 · ${streak}일 연속 학습\n오늘 ${todayAttempts.length}건 심사 · 누적 ${attempts.length}건 · 정답률 ${accuracy}%`;try{await navigator.clipboard.writeText(text);setToast('학습 기록을 복사했습니다. 친구에게 붙여넣어 공유하세요.');}catch{download('나의_학습기록.txt',text,'text/plain');}}
const Progress=({value}:{value:number})=><div className="progress"><span style={{width:`${Math.min(100,value)}%`}}/></div>;
const Stat=({label,value,sub}:{label:string;value:string;sub:string})=><div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>;
const visibleNav=member?.isAdmin?nav:nav.filter(([key])=>key!=='bank');
return <div className={`app game-app ${session&&!finished?'playing':''}`}><div className="office-scenery" aria-hidden="true"/>
<div className="workspace"><header className="game-header"><a className="brand" href="/" aria-label="심사실 홈"><Scale size={25}/><span>보건법규 심사관<small>HEALTH LAW · REVIEW OFFICE</small></span></a><button className="install-button" onClick={accountAction}>{member?member.nickname:'로그인 · 가입'}</button><button className="install-button" onClick={installApp}><Smartphone size={16}/>{installPrompt?'앱 설치':'홈 화면에 추가'}</button><nav aria-label="게임 메뉴">{visibleNav.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>go(key)} disabled={busy}><Icon size={17}/><span>{label}</span>{key==='review'&&wrong.length>0&&<b>{wrong.length}</b>}</button>)}</nav></header>
<div className="game-hud"><div><span className="hud-chip">근무일 <b>{days.size+(!days.has(today)?1:0)}일차</b></span><span className="hud-chip"><ShieldCheck size={15}/> {chapters[level].role}</span><span className="hud-chip">사건 <b>{session?String(session.index+1).padStart(2,'0'):String(todayAttempts.length).padStart(2,'0')} / {session?String(session.queue.length).padStart(2,'0'):'05'}</b></span></div><div><span className="hud-chip"><Flame size={16}/> {streak}일</span><span className="hud-chip">Lv. {level+1} · {xp} EXP</span><button className="hud-chip" onClick={()=>setSound(!sound)} aria-pressed={sound}>효과음 {sound?'ON':'OFF'}</button></div></div>
<main>
{toast&&<div className="toast" role="status">{toast}</div>}{error&&<div className="error" role="alert">{error} {!ready&&<button onClick={load}>다시 불러오기</button>}</div>}{!ready&&!error&&<div className="notice">학습 기록을 불러오는 중입니다…</div>}
{session?finished?<section className="completion panel"><div className="finish-icon"><CheckCircle2 size={48}/></div><div className="eyebrow">심사 묶음 완료</div><h1>오늘도 판단의 근거가 쌓였습니다.</h1><p>{session.queue.length}건 중 {session.right}건 정답 · 오늘 누적 {todayAttempts.length}건</p><div className="stats-grid"><Stat label="이번 정답률" value={`${Math.round(session.right/session.queue.length*100)}%`} sub="현재 심사 묶음"/><Stat label="오늘의 목표" value={`${Math.min(5,todayAttempts.length)} / 5`} sub={todayAttempts.length>=5?'목표 달성':'조금만 더 심사해 보세요'}/><Stat label="재심사 대기" value={`${wrong.length}건`} sub="오답은 다시 만나요"/></div><button className="primary" onClick={()=>go(tab)}>심사실로 돌아가기 <ArrowRight size={18}/></button>{wrong.length>0&&<button className="secondary" onClick={()=>begin(wrong.slice(0,5),'review')}>오답 바로 재심사</button>}</section>:<>
<div className="scene-window"><div className="scene-label"><span>HEALTH LAW OFFICE</span><h2>{modes[session.mode]}</h2><button className="text-button" onClick={()=>go(tab)} disabled={busy}><ArrowLeft size={16}/> 업무 선택으로</button></div><div className="npc-dialog"><strong>{current!.sender}</strong><p>{result===null?'접수 서류를 제출했습니다. 법령 기준에 맞는지 심사 부탁드립니다.':result?'확인 감사합니다. 다음 절차를 준비하겠습니다.':'알겠습니다. 검토하신 법령 기준을 다시 확인하겠습니다.'}</p></div></div>
<div className="desk-workspace" key={current!.id}><section className="document"><div className="section-bar"><b>1</b> 민원 접수 <span>CASE {current!.id}</span></div><div className="document-body"><div className="chips"><span>{current!.law}</span><span>{current!.difficulty}</span><span>{session.mode==='audit'?'감사 재검토':'접수 완료'}</span></div><h1>{current!.title}</h1><p className="case-body">{current!.body}</p><div className="document-details"><div className="eyebrow">첨부 서류 · 제출 사항</div>{current!.details.map((v,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{v}</p></div>)}</div>{result!==null&&<div className={`ink-stamp ${current!.answer?'ink-green':'ink-red'}`} aria-label={`심사 결과 ${current!.answer?'승인':'반려'}`}>{current!.answer?'승인':'반려'}<small>심사 완료</small></div>}<div className="document-foot">제출자: {current!.sender} · 학습용 가상 사건</div></div></section>
<section className="law-book"><div className="section-bar"><b>2</b> 법령 검토 <button onClick={()=>{setHint(!hint);setUsedHint(true)}}><BookOpen size={15}/>{hint?'법전 접기':'법전 펼치기'}</button></div><div className="book-pages"><div className="book-main"><div className="book-heading">보건법규 법전</div><h2>{current!.law}</h2><span className="article-label">{current!.article}</span>{hint||result!==null?<><p className="rule-text">{current!.rule}</p><a href={current!.source} target="_blank" rel="noreferrer">법령 원문 확인 ↗</a><small>학습용 요약 · 2026. 9. 6. 기준</small></>:<div className="closed-law"><BookOpen size={43}/><p>먼저 스스로 판단해 보세요.<br/>필요하면 법전을 펼칠 수 있습니다.</p><button className="secondary" onClick={()=>{setHint(true);setUsedHint(true)}}>법전 펼치기</button></div>}</div><aside className="book-note"><strong>심사 요령</strong><p>누가 제출했나?</p><p>어떤 요건이 필요한가?</p><p>빠진 내용이 없는가?</p><span>근거를 확인하고<br/>도장을 찍으세요.</span></aside></div></section></div>
<div className="decision-console"><section className={`result-panel ${result===false?'wrong-result':''}`} role="status"><div className="section-bar"><b>4</b> 결과 / 해설</div><div className="result-copy">{result===null?<><h3>심사를 기다리고 있습니다.</h3><p>서류가 법령에 적합하면 승인,<br/>미충족 사항이 있으면 반려하세요.</p></>:<><h3>{result?'정확한 판단입니다.':'판단의 근거를 다시 확인하세요.'}</h3><p>{current!.explanation}</p></>}</div></section><section className="stamp-panel"><div className="section-bar"><b>3</b> 판단 <span>도장을 선택하세요</span></div><div className="decision-buttons"><button className="approve" disabled={busy||result!==null} onClick={()=>answer(true)}><Check size={26}/><span>승인<small>요건 충족</small></span></button><button className="reject" disabled={busy||result!==null} onClick={()=>answer(false)}><X size={26}/><span>반려<small>보완 필요</small></span></button></div><p className="stamp-hint">{busy?'심사 기록 저장 중…':result===null?'제출 서류와 관련 법령을 검토하세요.':`처리 결과: ${current!.answer?'승인':'반려'}`}</p></section><section className="growth-panel"><div className="section-bar"><b>5</b> 성장 <span>{result===null?'':result?'+20 EXP':'−5 EXP'}</span></div><div className="growth-body"><div className="growth-level"><ShieldCheck/><strong>Lv. {level+1}</strong><span>{xp} EXP</span></div><Progress value={level===4?100:xp%100}/><small>{chapters[level].role}</small><button className="primary full" disabled={result===null||busy} onClick={next}>{session.index===session.queue.length-1?'근무 결과 확인':'다음 민원 접수'}<ArrowRight size={17}/></button></div></section></div></>:

<>
{tab==='home'&&<><div className="scene-window home-scene"><div className="scene-label"><span>보건행정 심사실 · OPEN</span><h1>심사관님,<br/>오늘의 민원이 도착했습니다.</h1><p>서류를 읽고, 법전을 펼치고,<br/>당신의 판단을 찍어 주세요.</p></div><div className="npc-dialog"><strong>선임 심사관</strong><p>어서 오세요! 오늘은 {Math.max(0,5-todayAttempts.length)}건의 사건이 기다리고 있어요. 준비되면 업무를 시작해 주세요.</p></div></div><div className="start-desk"><section className="dispatch-folder"><div className="section-bar"><b>01</b> 오늘의 배정 업무 <span>사건 심사실</span></div><div className="folder-content"><span className="eyebrow">DAILY ASSIGNMENT</span><h2>오늘의 사건 5건</h2><p>의료법 · 지역보건법 · 보건의료기본법<br/>서류 심사부터 판단, 해설까지 한 번에.</p><div className="mission-row"><strong>{Math.min(5,todayAttempts.length)}<small> / 5건 처리</small></strong><span>{todayAttempts.length>=5?'오늘의 임무 완료':'심사 대기 중'}</span></div><Progress value={todayAttempts.length*20}/><button className="primary start-button" disabled={!ready} onClick={()=>{setTab('free');begin(freeQueue(),'free')}}><Stamp size={22}/> 바로 근무 시작 <ArrowRight size={20}/></button><p className="guest-note">{guest?'로그인 없이 플레이 · 이 브라우저의 게스트 기록으로 이어집니다.':'기존 계정의 학습 기록으로 이어집니다.'}</p></div></section><div className="desk-menu"><button className="menu-book" onClick={()=>go('story')}><Waypoints size={28}/><div><span>STORY MODE</span><h2>심사관의 업무일지</h2><p>5개 챕터 · 첫 출근부터 국가 보건 정책까지</p></div><ChevronRight/></button><button className="menu-book free-book" onClick={()=>go('free')}><BookOpen size={28}/><div><span>FREE REVIEW</span><h2>단원별 자유 심사</h2><p>원하는 법령을 골라 집중 심사</p></div><ChevronRight/></button><button className="menu-book audit-book" onClick={()=>go('review')}><RotateCcw size={27}/><div><span>AUDIT DESK</span><h2>감사 재심사 {wrong.length}건</h2><p>놓친 기준을 다시 확인하고 종결하세요.</p></div><ChevronRight/></button></div></div><div className="office-ledger"><span><Flame size={18}/> {streak}일 연속 근무</span><span>누적 심사 <b>{attempts.length}건</b></span><span>정답률 <b>{attempts.length?accuracy+'%':'—'}</b></span><span>직급 <b>Lv. {level+1}</b></span></div></>}
{tab==='story'&&<><div className="page-heading"><div><div className="eyebrow">STORY MODE</div><h1>심사관의 업무일지</h1><p>앞 장의 사건을 모두 처리하면 다음 임무가 열립니다.</p></div><span className="outline-badge">{xp} EXP · Lv. {level+1}</span></div><div className="story-list">{chapters.map((ch,i)=>{const unlocked=i===0||chapters.slice(0,i).every((_,n)=>storyDone(n)===storyTotal(n));const done=storyDone(i)===storyTotal(i);return <section className={`chapter panel ${!unlocked?'locked':''}`} key={i}><div className="chapter-num">{!unlocked?<LockKeyhole size={24}/>:done?<Check size={25}/>:String(i+1).padStart(2,'0')}</div><div className="chapter-copy"><div className="eyebrow">CHAPTER {i+1} · {ch.role}</div><h2>{ch.title}</h2><p>{ch.intro}</p><Progress value={storyDone(i)/storyTotal(i)*100}/><small>{storyDone(i)} / {storyTotal(i)}건 처리</small></div><button className={unlocked?'primary':'secondary'} disabled={!unlocked||!ready} onClick={()=>begin(bank.filter(c=>c.chapter===i&&(done||!attempts.some(a=>a.case_id===c.id&&a.mode==='story'))),'story')}>{done?'다시 심사':unlocked?'임무 시작':'이전 장 완료 필요'}{unlocked&&<ArrowRight size={16}/>}</button></section>})}</div><section className="audit-banner"><RotateCcw/><div><h3>감사 재심사</h3><p>자유 심사와 스토리의 오답 {wrong.length}건이 함께 모였습니다.</p></div><button className="secondary" disabled={!wrong.length||!ready} onClick={()=>begin(wrong.slice(0,5),'audit')}>감사 시작</button></section><p className="small">직급은 학습을 위한 게임 설정이며 실제 행정기관의 승진 체계와 다릅니다.</p></>}
{tab==='free'&&<><div className="page-heading"><div><div className="eyebrow">FREE REVIEW</div><h1>자유 심사</h1><p>학습할 법령을 고르세요. 한 번에 최대 5건씩 무작위로 심사합니다.</p></div></div><div className="filter-row"><div className="tabs">{['전체',...laws].map(l=><button key={l} className={filter===l?'selected':''} onClick={()=>setFilter(l)}>{l}</button>)}</div><label>난이도 <select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['전체','기초','응용','심화'].map(d=><option key={d}>{d}</option>)}</select></label></div><section className="panel free-start"><div><div className="eyebrow">선택한 심사 범위</div><h2>{filter==='전체'?'전 법령 종합 심사':filter}</h2><p>{bank.filter(c=>(filter==='전체'||c.law===filter)&&(difficulty==='전체'||c.difficulty===difficulty)).length}개 사건 · {difficulty} 난이도 · 법령 도움말 제공</p></div><button className="primary" disabled={!ready||!freeQueue().length} onClick={()=>begin(freeQueue(),'free')}>심사 시작 <ArrowRight size={18}/></button></section><div className="law-grid">{laws.map(l=>{const records=attempts.filter(a=>bank.find(c=>c.id===a.case_id)?.law===l);return <button className="panel law-card" key={l} onClick={()=>setFilter(l)}><BookOpen size={27}/><h2>{l}</h2><p>{bank.filter(c=>c.law===l).length}개 사건</p><Progress value={records.length?records.filter(a=>a.correct).length/records.length*100:0}/><small>{records.length?`정답률 ${Math.round(records.filter(a=>a.correct).length/records.length*100)}% · ${records.length}회 풀이`:'아직 심사한 사건이 없습니다.'}</small></button>})}</div></>}
{tab==='review'&&<><div className="page-heading"><div><div className="eyebrow">REVIEW INBOX</div><h1>오답 재심사함 <span className="count-badge">{wrong.length}</span></h1><p>다시 맞힌 사건은 자동으로 종결됩니다.</p></div><button className="primary" disabled={!ready||!wrong.length} onClick={()=>begin(wrong.slice(0,5),'review')}>재심사 시작 <ArrowRight size={18}/></button></div>{wrong.length?<div className="panel case-list">{wrong.map(c=><button key={c.id} onClick={()=>begin([c],'review')}><div className="file-icon"><Files/></div><div><small>{c.law} · {c.article}</small><h3>{c.title}</h3><p>{attempts.filter(a=>a.case_id===c.id&&!a.correct).length}회 오답 · 재검토 대기</p></div><ArrowRight/></button>)}</div>:<section className="panel empty"><CheckCircle2 size={48}/><h2>재심사할 사건이 없습니다.</h2><p>{attempts.length?'모든 오답을 해결했습니다. 새로운 사건을 만나보세요.':'심사를 시작하면 틀린 사건이 이곳에 자동으로 모입니다.'}</p><button className="primary" onClick={()=>go('free')}>자유 심사로 이동</button></section>}</>}
{tab==='stats'&&<><div className="page-heading"><div><div className="eyebrow">LEARNING RECORD</div><h1>작은 심사, 쌓이는 실력</h1><p>모든 모드의 기록을 하나로 모았습니다. 날짜는 한국 시간을 기준으로 합니다.</p></div><button className="secondary" onClick={exportCSV} disabled={!attempts.length}><Download size={17}/> 기록 CSV</button></div><div className="stats-grid"><Stat label="학습 경험치" value={`${xp} EXP`} sub={`Lv. ${level+1} ${chapters[level].role}`}/><Stat label="총 학습 시간" value={`${Math.round(attempts.reduce((s,a)=>s+a.duration,0)/60)}분`} sub="문항별 응답 시간 합계"/><Stat label="전체 정답률" value={attempts.length?`${accuracy}%`:'—'} sub={`${attempts.length}회 중 ${correctCount}회 정답`}/></div><div className="home-grid"><section className="panel"><h2>최근 7일 학습</h2><div className="bar-chart">{Array.from({length:7},(_,i)=>{const dt=new Date(today+'T12:00:00+09:00');dt.setDate(dt.getDate()-6+i);const count=days.get(day(dt))||0;const max=Math.max(5,...Array.from(days.values()));return <div key={i}><strong>{count}</strong><div className="bar-track"><span style={{height:`${Math.max(2,count/max*100)}%`}}/></div><small>{dt.getMonth()+1}/{dt.getDate()}</small></div>})}</div></section><section className="panel"><h2>모드별 학습</h2>{Object.entries(modes).map(([k,v])=>{const a=attempts.filter(a=>a.mode===k);return <div className="mode-stat" key={k}><span>{v}</span><strong>{a.length}건</strong><small>{a.length?Math.round(a.filter(a=>a.correct).length/a.length*100)+'% 정답':'기록 없음'}</small></div>})}<button className="secondary full" onClick={share}><Share2 size={17}/> 친구에게 보낼 기록 복사</button></section></div><section className="panel"><h2>법령별 학습 현황</h2>{laws.map(l=>{const a=attempts.filter(a=>bank.find(c=>c.id===a.case_id)?.law===l);return <div className="mastery" key={l}><strong>{l}</strong><Progress value={a.length?a.filter(a=>a.correct).length/a.length*100:0}/><span>{a.length?Math.round(a.filter(a=>a.correct).length/a.length*100)+'%':'—'} · {a.length}회</span></div>})}<p className="small">정답률은 반복 풀이와 도움말 사용을 포함하며 국가고시 예상 성적을 의미하지 않습니다.</p></section></>}
{tab==='bank'&&member?.isAdmin&&<><div className="page-heading"><div><div className="eyebrow">ADMIN CASE LIBRARY</div><h1>문항 관리</h1><p>이 화면은 관리자에게만 보입니다. 저장한 문항은 모든 이용자에게 적용됩니다.</p></div><button className="secondary" onClick={()=>download('보건법규_문제은행.json',JSON.stringify(bank,null,2))}><Download size={17}/> 문항 내보내기</button></div><section className="notice"><strong>문항 검수 안내</strong><p>추가 전 법령 원문, 정답, 해설, 출처 링크를 확인하세요. 같은 문항 ID로 저장하면 기존 공용 문항을 수정합니다.</p></section><section className="panel import-panel"><div><h3>공용 문항 추가·수정</h3><p>양식 파일을 내려받아 사례·정답·해설·법령 출처를 작성한 뒤 가져오세요. 저장하면 다른 사용자의 게임에도 반영됩니다.</p></div><div className="button-row"><button className="secondary" onClick={()=>download('문항_추가_양식.json',JSON.stringify([{...bank[0],id:'custom-001',origin:'팀 제작 · 검수자와 검수일 기재'}],null,2))}>양식 받기</button><button className="primary" disabled={!ready||busy} onClick={()=>fileRef.current?.click()}><Upload size={17}/> 공용 문항 저장</button><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e=>e.target.files?.[0]&&importCases(e.target.files[0])}/></div></section><input className="search" placeholder="사건명, 법령, 조문 검색" aria-label="문항 검색" value={search} onChange={e=>setSearch(e.target.value)}/><div className="bank-list">{bank.filter(c=>(c.title+c.law+c.article).includes(search)).map(c=><details className="panel" key={c.id}><summary><span className="case-code">{c.id}</span><div><small>{c.law} {c.article} · {c.difficulty}</small><strong>{c.title}</strong></div><ChevronRight size={18}/></summary><div className="bank-detail"><p>{c.body}</p><ul>{c.details.map((v,i)=><li key={i}>{v}</li>)}</ul><strong>정답: {c.answer?'승인':'반려'}</strong><p>{c.explanation}</p><a href={c.source} target="_blank" rel="noreferrer">국가법령정보센터 원문 ↗</a><p className="small">{c.origin}</p></div></details>)}</div></>}
</>}
<footer><span>보건법규 심사관 · 캡스톤 3조</span><span>{guest?'게스트 플레이 · 쿠키 삭제 시 기록 연결이 끊어집니다.':'계정 기록 사용 중'}</span></footer></main><nav className="mobile-tabbar" aria-label="앱 하단 메뉴">{visibleNav.slice(0,5).map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>go(key)} disabled={busy}><Icon size={21}/><span>{label.replace('오늘의 ','').replace(' 모드','')}</span>{key==='review'&&wrong.length>0&&<b>{wrong.length}</b>}</button>)}</nav></div></div>;
}
